# Generated by Django 3.0.5 on 2022-10-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Surgical Oncologist', 'Surgical Oncologist'), ('Radiation Oncologist', 'Radiation Oncologist'), ('Gynecologic Oncologist', 'Gynecologic Oncologist'), ('Pediatric Oncologist', 'Pediatric Oncologist'), ('Hematologist-Oncologist', 'Hematologist-Oncologist'), ('Neuro-Oncologist', 'Neuro-Oncologist')], default='Cardiologist', max_length=50),
        ),
    ]
